name: stars
description: A flutter app to invest time to setup architecture basement
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.1

dependencies:
  auto_route: ^5.0.4
  auto_route_generator: ^5.0.3
  connectivity_plus: ^3.0.3
  dio: ^5.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_redux: ^0.10.0
  go_router: ^6.0.7
  helper_options: ^0.1.0+2
  intl: ^0.17.0
  json_annotation: ^4.8.0
  redux_epics: ^0.15.1

dev_dependencies:
  build: ^2.3.1
  build_runner: ^2.3.2
  built_value_generator: ^8.4.3
  built_value: ^8.4.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
